# Základy práce v pythonu

<div class="alert alert-block alert-info"><b>Tip: </b> Tento soubor je mozne stahnout ve forme <i>*.ipynb</i> nebo jako <i>*.pdf</i>.</div>

<div class="alert alert-block alert-success"><b>On-line interaktivni verze: </b> Pro spusteni interaktivni verze kliknete ve vrchnim menu na raketu a zvolte <i>Binder</i>, ve kterem lze JN (Jupyter Notebook) upravovat. Volba <i>Live Code</i> umozni pouze spoustet radky s kodem.</div>

## Interaktivni Jupyter notebook

Napiste `print('Hello, World!')` a stisknete `Shift` `+` `Enter` (nebo `Ctrl` `+` `Enter`)

In [6]:
print('Hello, World')

Hello, World


Pomoci klavesy `b` vlozite dalsi radek. 
* Stisknete `b`.

Odstraneni radku: vyberte radek a stisknete `d` `+` `d`

Klavesou `a` vlozite novy radek nad prave vybrany. 
1. Stisknete `a`. 
2. Vyberte tento novy radek a stisknete `m`. Nyni lze do radku misto kodu zapisovat text.
3. Zadavani ukoncite stisknutim `Shift` `+` `Enter`.
4. Pokud chcete radek prevest na kod, stisknete `y`.


**Pro nápovědu stisknete `h`.**

## Python

Jednoradkovy komentar se zadava za znak `#`, vice radku lze zakomentovat pomoci `"""` a `"""`

In [5]:
# toto je komentar
"""
Komentar
na vice
radku...
"""
print("Hello, World!") 



Hello, World!


### Jednoduche pocitani s promennymi

Inicializace promennych `a`, `b` a zakladni aritmeticke operace a vypis vysledku:

In [49]:
a=43
b=5.5

soucet=a+b
rozdil=a-b
soucin=a*b
podil=a/b
mocnina=a**b

# vypis
print('Soucet ',soucet)
print('Rozdil ',rozdil)
print('Soucin ',soucin)
print('Podil ',podil)
print('Mocnina ',mocnina)



Soucet  48.5
Rozdil  37.5
Soucin  236.5
Podil  7.818181818181818
Mocnina  963998827.5258548


<div class="alert alert-block alert-warning"><b>Cviceni 01.01: </b> Vypoctete objem jehlanu o stranach 3 a 4 majiciho vysku 7. </div>

In [50]:
a=3
b=4
v=7
S=a*b
V=1/3*S*v
print(V)

28.0


List a range

***

### Podminkove cykly

#### If ... else

<div class="alert alert-block alert-danger"><b>Pozor:</b> vnitrni casti kodu je <b>nutne</b> odsadit, obvykle se pouzivaji <b>ctyri mezery</b>.</div>

Za klicovymi slovy `if` a `else` musime psat `:`.

In [36]:
cislo = 0
if cislo > 0:
    print(cislo, "je kladne.")
elif cislo <0:
    print(cislo, "je zaporne")
else:
    print("musi to byt nula")    
print("Tento text se vypise vzdy.")

musi to byt nula
Tento text se vypise vzdy.


#### For ...

In [38]:
for x in range(10):
    print(x)

0
1
2
3
4
5
6
7
8
9


#### While...

In [46]:
cislo = 0
while cislo < 10:
  print(cislo)
  cislo = cislo+1 # ekvivalenti zapis je take: cislo += 1

0
1
2
3
4
5
6
7
8
9


break continue

***

### List (seznam)

Prvky seznamu vkladame do hranatych zavorek.

In [18]:
seznam=[0,1,2,3]
print(seznam[0])

0


<div class="alert alert-block alert-danger"><b>Pozor:</b> v seznamu <code>list</code> ma prvni prvek index <b>0</b>!</div>

#### Hledani v seznamech

In [5]:
seznam=[0,1,2,3,"a","B"]
print(0 in seznam)

True


Jak najit index hledneho prvku v seznamu:

In [11]:
# jaky index v seznamu ma prvek "a"?
index_hledaneho_prvku = seznam.index("a")
print('Prvek "a" ma v seznamu index: ',index_hledaneho_prvku)

Prvek "a" ma v seznamu index:  4


***

### Funkce

In [24]:
def objem_jehlanu(a,b,v):
  return 1/3*a*b*v

print("Objem jehlanu = ",objem_jehlanu(2,3,4))

Objem jehlanu =  8.0


***

### Numericka knihovna numpy

Pro importovani numericke knihovny `numpy` pouzijeme prikaz:

In [25]:
import numpy as np

#### Pole

Pole (vektor, matice) lze vytvaret pomoci funkce `array`:

In [26]:
# vektor
a = np.array([1, 2, 3])

# matice
matice = np.array([[1,2,3],[4,5,6],[7,8,9]])

<div class="alert alert-block alert-danger"><b>Pozor:</b> v poli <code>array</code> ma prvni prvek index <b>0</b>!</div>

Rozmery pole zjisitme pomoci funkce `shape`:

In [27]:
print(a.shape)
print(matice.shape)

(3,)
(3, 3)


Funkce `size` vrati pocet prvku v poli:

In [29]:
print(a.size)
print(matice.size)

3
9


Pro vytvareni poli lze pouzivat generatory `arange`,`linspace`,`logspace`,`ones`,`zeros`,`eye`,`random`:

In [30]:
# vytvorime pole od 0 do 10 s krokem 1
pole = np.arange(0,10,1)
print(pole)

[0 1 2 3 4 5 6 7 8 9]


In [33]:
# vytovrime pole od 0 do 10 s poctem prvku 20
pole = np.linspace(0,10,20)
print(pole)

[ 0.          0.52631579  1.05263158  1.57894737  2.10526316  2.63157895
  3.15789474  3.68421053  4.21052632  4.73684211  5.26315789  5.78947368
  6.31578947  6.84210526  7.36842105  7.89473684  8.42105263  8.94736842
  9.47368421 10.        ]


In [41]:
# vytovrime pole od 0 do 10 s poctem prvku 20 v logaritmickem meritku  (log se zakladem 10)
pole = np.logspace(0,10,20,base=10)
print(pole)

[1.00000000e+00 3.35981829e+00 1.12883789e+01 3.79269019e+01
 1.27427499e+02 4.28133240e+02 1.43844989e+03 4.83293024e+03
 1.62377674e+04 5.45559478e+04 1.83298071e+05 6.15848211e+05
 2.06913808e+06 6.95192796e+06 2.33572147e+07 7.84759970e+07
 2.63665090e+08 8.85866790e+08 2.97635144e+09 1.00000000e+10]


In [43]:
# vytovrime matici 2x2 obsahujici same nuly
pole = np.zeros((2,2))
print(pole)

[[0. 0.]
 [0. 0.]]


In [45]:
# vytovrime matici 3x3 obsahujici same jednicky
pole = np.ones((3,3))
print(pole)

[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]


In [48]:
# vytovrime matici 3x3 s jednickami na diagonale, ostatni hodnoty jsou nulove
pole = np.eye(3)
print(pole)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


Pro pristup k prvkum matice pouzivame syntaxi `[min:max]`

In [49]:
matice = np.array([[1,2,3],[4,5,6],[7,8,9]])
print(matice)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [51]:
prvni_radek = matice[0,:]
print(prvni_radek)

[1 2 3]


In [53]:
prvni_sloupec = matice[:,0]
print(prvni_sloupec)

[1 4 7]


Nasobeni matic a vektoru se provadi pomoci operatoru `dot`:

In [60]:
# matice 2x3
A = np.array([[1,2,3],[4,5,6]])
print(A)
print(A.shape)

# matice 3x2
B = np.array([[1,2],[3,4],[5,6]])
print(B)
print(B.shape)

# vysledek
C = np.dot(A,B)
print(C)


[[1 2 3]
 [4 5 6]]
(2, 3)
[[1 2]
 [3 4]
 [5 6]]
(3, 2)
[[22 28]
 [49 64]]


<div class="alert alert-block alert-danger"><b>Pozor:</b> operace <b>C*C</b> nasobi matice po prvcich (neni to maticove nasobeni)</div>

In [64]:
# maticove nasobeni
print(np.dot(C,C))

# nasobeni po prvcich
print(C*C)

[[1856 2408]
 [4214 5468]]
[[ 484  784]
 [2401 4096]]


#### Funkce

`numpy` obsahuje casto pouzivane funkce a konstanty (napr. `sqrt`, `log`, `sin`, `abs`, `e`, `pi`, ...):

In [79]:
print(np.sqrt(5))
print(np.log(5))
print(np.sin(5))
print(np.abs(-3))
print(np.e)
print(np.pi)

2.23606797749979
1.6094379124341003
-0.9589242746631385
3
2.718281828459045
3.141592653589793


Zjistime soucet prvku (`sum`), maximum (`max`), minimum (`min`), prumernou hodnotou (`average`), smerodatnou odchylku (`std`) a rozptyl (`var`) u matice `A`:

In [78]:
print(A)

soucet = np.sum(A)
print(soucet)

maximum = np.max(A)
print(maximum)

minimum = np.min(A)
print(minimum)

prumer = np.average(A)
print(prumer)

smerodatna_odchylka = np.std(A)
print(smerodatna_odchylka)

rozptyl = np.var(A)
print(rozptyl)

[[1 2 3]
 [4 5 6]]
21
6
1
3.5
1.707825127659933
2.9166666666666665


Index prvku v matici lze najit pomoci funkce `argwhere`:

In [91]:
index_hledaneho_prvku = np.argwhere(A == 3)
print(index_hledaneho_prvku)

[[0 2]]
